<script lang="ts">
    /**
     * AI Summary Component
     * Displays AI-generated session analysis and insights
     */
    import { createEventDispatcher } from "svelte";
    import type { AISessionSummary } from "$lib/api/ai";
    import {
        generateSessionSummary,
        saveSessionSummary,
        getSessionSummary,
        getAIProviderStatus,
    } from "$lib/api/ai";
    import type { OplogSession } from "$lib/api/oplog";
    import type { ChatMessage } from "$lib/api/chatlog";

    export let session: OplogSession;
    export let chatMessages: ChatMessage[] = [];

    const dispatch = createEventDispatcher<{
        generated: AISessionSummary;
    }>();

    let summary: AISessionSummary | null = null;
    let loading = false;
    let error: string | null = null;
    let providerStatus = getAIProviderStatus();

    // Provider selection: 'auto', 'openai', or 'gemini'
    let selectedProvider: "auto" | "openai" | "gemini" = "auto";

    // Load existing summary on mount
    $: if (session?.id) {
        loadExistingSummary();
    }

    async function loadExistingSummary() {
        try {
            summary = await getSessionSummary(session.id);
        } catch (e) {
            console.error("Failed to load existing summary:", e);
        }
    }

    async function generateSummary() {
        // Validate provider selection
        if (selectedProvider === "openai" && !providerStatus.openai) {
            error = "ไม่ได้ตั้งค่า OpenAI API Key";
            return;
        }
        if (selectedProvider === "gemini" && !providerStatus.gemini) {
            error = "ไม่ได้ตั้งค่า Gemini API Key";
            return;
        }
        if (
            selectedProvider === "auto" &&
            !providerStatus.openai &&
            !providerStatus.gemini
        ) {
            error = "ไม่ได้ตั้งค่า API Key (OpenAI หรือ Gemini)";
            return;
        }

        loading = true;
        error = null;

        try {
            const generatedSummary = await generateSessionSummary(
                session,
                chatMessages,
                selectedProvider,
            );
            summary = await saveSessionSummary(generatedSummary);
            dispatch("generated", summary);
        } catch (e) {
            error =
                e instanceof Error ? e.message : "Failed to generate summary";
            console.error("AI Summary error:", e);
        } finally {
            loading = false;
        }
    }

    function copyToClipboard() {
        if (!summary) return;

        const text = `
🤖 AI Session Summary
━━━━━━━━━━━━━━━━━━━━━

📝 ${summary.summary}

📊 Highlights:
• Volume: ${summary.highlights.totalVolume}
• Transactions: ${summary.highlights.transactionCount}
• Trend: ${summary.highlights.dominantAction}
• Spread: ${summary.highlights.spreadTrend}

💡 Operational Insights:
${summary.operationalInsights.map((i) => `• ${i}`).join("\n")}

📈 Management Insights:
${summary.managementInsights.map((i) => `• ${i}`).join("\n")}

✅ Recommendations:
${summary.recommendations.map((r) => `• ${r}`).join("\n")}

${summary.riskFlags.length > 0 ? `⚠️ Risk Flags:\n${summary.riskFlags.map((f) => `• ${f}`).join("\n")}` : ""}

Generated by: ${summary.provider} (${summary.model})
        `.trim();

        navigator.clipboard.writeText(text);
    }

    function formatDate(dateStr: string | undefined): string {
        if (!dateStr) return "";
        return new Date(dateStr).toLocaleString("th-TH", {
            day: "numeric",
            month: "short",
            hour: "2-digit",
            minute: "2-digit",
        });
    }
</script>

<section class="ai-summary-container">
    <header class="section-header">
        <div class="header-left">
            <span class="icon">🤖</span>
            <h3>AI Session Summary</h3>
            {#if summary}
                <span
                    class="provider-badge"
                    class:openai={summary.provider === "openai"}
                >
                    {summary.provider === "openai" ? "GPT-4" : "Gemini"}
                </span>
            {/if}
        </div>
        <div class="header-actions">
            {#if !loading}
                <!-- Provider Selector -->
                <div class="provider-selector">
                    <button
                        class="provider-btn"
                        class:active={selectedProvider === "auto"}
                        on:click={() => (selectedProvider = "auto")}
                        disabled={!providerStatus.openai &&
                            !providerStatus.gemini}
                        title="Auto: ลอง GPT-4 ก่อน, fallback เป็น Gemini"
                    >
                        ⚡ Auto
                    </button>
                    <button
                        class="provider-btn openai"
                        class:active={selectedProvider === "openai"}
                        on:click={() => (selectedProvider = "openai")}
                        disabled={!providerStatus.openai}
                        title="GPT-4o-mini"
                    >
                        🟢 GPT
                    </button>
                    <button
                        class="provider-btn gemini"
                        class:active={selectedProvider === "gemini"}
                        on:click={() => (selectedProvider = "gemini")}
                        disabled={!providerStatus.gemini}
                        title="Gemini 1.5 Flash"
                    >
                        🔵 Gemini
                    </button>
                </div>

                <button
                    class="btn-generate"
                    on:click={generateSummary}
                    disabled={!providerStatus.openai && !providerStatus.gemini}
                >
                    {summary ? "🔄 Re-generate" : "✨ Generate"}
                </button>
            {/if}
        </div>
    </header>

    <div class="content">
        {#if loading}
            <div class="loading-state">
                <div class="spinner"></div>
                <p>
                    กำลังวิเคราะห์ด้วย {selectedProvider === "openai"
                        ? "GPT-4"
                        : selectedProvider === "gemini"
                          ? "Gemini"
                          : "AI"}... อาจใช้เวลา 5-10 วินาที
                </p>
            </div>
        {:else if error}
            <div class="error-state">
                <span class="error-icon">⚠️</span>
                <p>{error}</p>
                <button class="btn-retry" on:click={generateSummary}
                    >ลองใหม่</button
                >
            </div>
        {:else if !summary}
            <div class="empty-state">
                <span class="empty-icon">💭</span>
                <p>ยังไม่มี AI Summary สำหรับ Session นี้</p>
                {#if !providerStatus.openai && !providerStatus.gemini}
                    <p class="config-warning">
                        ⚠️ กรุณาตั้งค่า VITE_OPENAI_API_KEY หรือ
                        VITE_GEMINI_API_KEY ใน .env
                    </p>
                {:else}
                    <p class="hint">คลิกปุ่ม "Generate Summary" เพื่อสร้าง</p>
                {/if}
            </div>
        {:else}
            <!-- Summary Content -->
            <div class="summary-content">
                <!-- Main Summary -->
                <div class="summary-card main">
                    <div class="card-header">
                        <span class="card-icon">📝</span>
                        <span class="card-title">สรุปภาพรวม</span>
                    </div>
                    <p class="summary-text">{summary.summary}</p>
                </div>

                <!-- Highlights Grid -->
                <div class="highlights-grid">
                    <div class="highlight-item">
                        <span class="hl-label">Volume</span>
                        <span class="hl-value"
                            >{summary.highlights.totalVolume}</span
                        >
                    </div>
                    <div class="highlight-item">
                        <span class="hl-label">Transactions</span>
                        <span class="hl-value"
                            >{summary.highlights.transactionCount}</span
                        >
                    </div>
                    <div class="highlight-item">
                        <span class="hl-label">Trend</span>
                        <span
                            class="hl-value trend"
                            class:buy={summary.highlights.dominantAction ===
                                "BUY"}
                            class:sell={summary.highlights.dominantAction ===
                                "SELL"}
                        >
                            {summary.highlights.dominantAction}
                        </span>
                    </div>
                    <div class="highlight-item wide">
                        <span class="hl-label">Spread</span>
                        <span class="hl-value"
                            >{summary.highlights.spreadTrend}</span
                        >
                    </div>
                </div>

                <!-- Insights Cards -->
                <div class="insights-grid">
                    {#if summary.operationalInsights.length > 0}
                        <div class="summary-card insights">
                            <div class="card-header">
                                <span class="card-icon">⚙️</span>
                                <span class="card-title"
                                    >Operation Insights</span
                                >
                            </div>
                            <ul class="insight-list">
                                {#each summary.operationalInsights as insight}
                                    <li>{insight}</li>
                                {/each}
                            </ul>
                        </div>
                    {/if}

                    {#if summary.managementInsights.length > 0}
                        <div class="summary-card insights">
                            <div class="card-header">
                                <span class="card-icon">📊</span>
                                <span class="card-title"
                                    >Management Insights</span
                                >
                            </div>
                            <ul class="insight-list">
                                {#each summary.managementInsights as insight}
                                    <li>{insight}</li>
                                {/each}
                            </ul>
                        </div>
                    {/if}
                </div>

                <!-- Recommendations -->
                {#if summary.recommendations.length > 0}
                    <div class="summary-card recommendations">
                        <div class="card-header">
                            <span class="card-icon">💡</span>
                            <span class="card-title">Recommendations</span>
                        </div>
                        <ul class="insight-list">
                            {#each summary.recommendations as rec}
                                <li>{rec}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}

                <!-- Risk Flags -->
                {#if summary.riskFlags.length > 0}
                    <div class="summary-card risk">
                        <div class="card-header">
                            <span class="card-icon">⚠️</span>
                            <span class="card-title">Risk Flags</span>
                        </div>
                        <ul class="insight-list">
                            {#each summary.riskFlags as flag}
                                <li>{flag}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}

                <!-- Footer -->
                <div class="summary-footer">
                    <span class="generated-info">
                        Generated: {formatDate(summary.created_at)}
                    </span>
                    <button class="btn-copy" on:click={copyToClipboard}>
                        📋 Copy
                    </button>
                </div>
            </div>
        {/if}
    </div>
</section>

<style>
    .ai-summary-container {
        background: var(--color-bg);
        border: 1px solid var(--color-border-light);
        border-radius: 16px;
        overflow: hidden;
    }

    .section-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem 1.25rem;
        background: linear-gradient(
            135deg,
            rgba(102, 126, 234, 0.1),
            rgba(118, 75, 162, 0.1)
        );
        border-bottom: 1px solid var(--color-border-light);
    }

    .header-left {
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }

    .icon {
        font-size: 1.5rem;
    }

    .section-header h3 {
        margin: 0;
        font-size: 1.125rem;
        font-weight: 600;
        color: var(--color-text);
    }

    .provider-badge {
        padding: 0.25rem 0.5rem;
        font-size: 0.6875rem;
        font-weight: 600;
        border-radius: 6px;
        background: rgba(118, 75, 162, 0.15);
        color: #764ba2;
    }

    .provider-badge.openai {
        background: rgba(16, 163, 127, 0.15);
        color: #10a37f;
    }

    .header-actions {
        display: flex;
        gap: 0.5rem;
        align-items: center;
        flex-wrap: wrap;
    }

    /* Provider Selector Toggle */
    .provider-selector {
        display: flex;
        gap: 0.25rem;
        background: var(--color-bg-secondary);
        border-radius: 8px;
        padding: 0.25rem;
    }

    .provider-btn {
        padding: 0.375rem 0.625rem;
        font-size: 0.75rem;
        font-weight: 500;
        border: none;
        border-radius: 6px;
        background: transparent;
        color: var(--color-text-tertiary);
        cursor: pointer;
        transition: all 0.15s;
        white-space: nowrap;
    }

    .provider-btn:hover:not(:disabled) {
        background: var(--color-bg-tertiary);
        color: var(--color-text-secondary);
    }

    .provider-btn.active {
        background: var(--color-bg);
        color: var(--color-text);
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    .provider-btn.active.openai {
        color: #10a37f;
    }

    .provider-btn.active.gemini {
        color: #4285f4;
    }

    .provider-btn:disabled {
        opacity: 0.4;
        cursor: not-allowed;
    }

    @media (max-width: 640px) {
        .header-actions {
            flex-direction: column;
            gap: 0.5rem;
            width: 100%;
        }

        .provider-selector {
            width: 100%;
            justify-content: center;
        }

        .btn-generate {
            width: 100%;
        }
    }

    .btn-generate {
        padding: 0.5rem 1rem;
        font-size: 0.875rem;
        font-weight: 600;
        border: none;
        border-radius: 8px;
        background: linear-gradient(135deg, #667eea, #764ba2);
        color: white;
        cursor: pointer;
        transition: all 0.2s;
    }

    .btn-generate:hover:not(:disabled) {
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
    }

    .btn-generate:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .content {
        padding: 1.25rem;
    }

    /* Loading State */
    .loading-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        padding: 3rem;
    }

    .spinner {
        width: 40px;
        height: 40px;
        border: 3px solid var(--color-border-light);
        border-top-color: #667eea;
        border-radius: 50%;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }

    .loading-state p {
        color: var(--color-text-secondary);
        font-size: 0.9375rem;
    }

    /* Empty State */
    .empty-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 0.5rem;
        padding: 3rem;
        text-align: center;
    }

    .empty-icon {
        font-size: 3rem;
        opacity: 0.5;
    }

    .empty-state p {
        margin: 0;
        color: var(--color-text-tertiary);
    }

    .config-warning {
        color: #ff9500 !important;
        font-size: 0.875rem;
    }

    .hint {
        font-size: 0.8125rem;
    }

    /* Error State */
    .error-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 0.75rem;
        padding: 2rem;
        background: rgba(255, 59, 48, 0.1);
        border-radius: 12px;
    }

    .error-icon {
        font-size: 2rem;
    }

    .error-state p {
        margin: 0;
        color: #ff3b30;
    }

    .btn-retry {
        padding: 0.5rem 1rem;
        font-size: 0.875rem;
        background: var(--color-bg);
        border: 1px solid var(--color-border-light);
        border-radius: 8px;
        cursor: pointer;
    }

    /* Summary Content */
    .summary-content {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    .summary-card {
        padding: 1rem;
        background: var(--color-bg-secondary);
        border-radius: 12px;
    }

    .summary-card.main {
        background: linear-gradient(
            135deg,
            rgba(102, 126, 234, 0.08),
            rgba(118, 75, 162, 0.08)
        );
    }

    .summary-card.risk {
        background: rgba(255, 59, 48, 0.08);
        border: 1px solid rgba(255, 59, 48, 0.2);
    }

    .card-header {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        margin-bottom: 0.75rem;
    }

    .card-icon {
        font-size: 1.125rem;
    }

    .card-title {
        font-size: 0.875rem;
        font-weight: 600;
        color: var(--color-text-secondary);
    }

    .summary-text {
        margin: 0;
        font-size: 1rem;
        line-height: 1.6;
        color: var(--color-text);
    }

    /* Highlights Grid */
    .highlights-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 0.75rem;
    }

    @media (max-width: 640px) {
        .highlights-grid {
            grid-template-columns: repeat(2, 1fr);
        }
    }

    .highlight-item {
        display: flex;
        flex-direction: column;
        gap: 0.25rem;
        padding: 0.75rem;
        background: var(--color-bg-secondary);
        border-radius: 10px;
    }

    .highlight-item.wide {
        grid-column: span 2;
    }

    @media (max-width: 640px) {
        .highlight-item.wide {
            grid-column: span 2;
        }
    }

    .hl-label {
        font-size: 0.6875rem;
        color: var(--color-text-tertiary);
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }

    .hl-value {
        font-size: 1.125rem;
        font-weight: 700;
        color: var(--color-text);
    }

    .hl-value.trend.buy {
        color: #34c759;
    }

    .hl-value.trend.sell {
        color: #ff3b30;
    }

    /* Insights Grid */
    .insights-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 0.75rem;
    }

    @media (max-width: 768px) {
        .insights-grid {
            grid-template-columns: 1fr;
        }
    }

    .insight-list {
        margin: 0;
        padding-left: 1.25rem;
        font-size: 0.9375rem;
        line-height: 1.6;
        color: var(--color-text-secondary);
    }

    .insight-list li {
        margin-bottom: 0.375rem;
    }

    /* Footer */
    .summary-footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding-top: 1rem;
        border-top: 1px solid var(--color-separator);
    }

    .generated-info {
        font-size: 0.75rem;
        color: var(--color-text-tertiary);
    }

    .btn-copy {
        padding: 0.375rem 0.75rem;
        font-size: 0.8125rem;
        font-weight: 500;
        background: var(--color-bg-secondary);
        border: 1px solid var(--color-border-light);
        border-radius: 6px;
        cursor: pointer;
        transition: all 0.15s;
    }

    .btn-copy:hover {
        background: var(--color-bg-tertiary);
    }
</style>
