<script lang="ts">
    /**
     * Daily Summary Component
     * Displays AI-generated daily report for management
     */
    import { createEventDispatcher } from "svelte";
    import type { DailySummary } from "$lib/api/ai";
    import {
        generateDailySummary,
        saveDailySummary,
        getDailySummary,
        getAIProviderStatus,
    } from "$lib/api/ai";
    import type { OplogSession } from "$lib/api/oplog";

    export let logDate: string;
    export let sessions: OplogSession[] = [];

    const dispatch = createEventDispatcher<{
        generated: DailySummary;
    }>();

    let summary: DailySummary | null = null;
    let loading = false;
    let error: string | null = null;
    let providerStatus = getAIProviderStatus();
    let selectedProvider: "auto" | "openai" | "gemini" = "auto";

    // Load existing summary
    $: if (logDate) {
        loadExistingSummary();
    }

    async function loadExistingSummary() {
        try {
            summary = await getDailySummary(logDate);
        } catch (e) {
            console.error("Failed to load daily summary:", e);
        }
    }

    async function generateSummary() {
        if (sessions.length === 0) {
            error = "ไม่มี Session สำหรับวันนี้";
            return;
        }

        if (selectedProvider === "openai" && !providerStatus.openai) {
            error = "ไม่ได้ตั้งค่า OpenAI API Key";
            return;
        }
        if (selectedProvider === "gemini" && !providerStatus.gemini) {
            error = "ไม่ได้ตั้งค่า Gemini API Key";
            return;
        }
        if (
            selectedProvider === "auto" &&
            !providerStatus.openai &&
            !providerStatus.gemini
        ) {
            error = "ไม่ได้ตั้งค่า API Key";
            return;
        }

        loading = true;
        error = null;

        try {
            const generatedSummary = await generateDailySummary(
                logDate,
                sessions,
                selectedProvider,
            );
            summary = await saveDailySummary(generatedSummary);
            dispatch("generated", summary);
        } catch (e) {
            error =
                e instanceof Error ? e.message : "Failed to generate summary";
            console.error("Daily Summary error:", e);
        } finally {
            loading = false;
        }
    }

    function formatVolume(v: number): string {
        if (v >= 1000000) return `${(v / 1000000).toFixed(2)}M`;
        if (v >= 1000) return `${(v / 1000).toFixed(1)}K`;
        return v.toLocaleString();
    }

    function formatDuration(minutes: number): string {
        const h = Math.floor(minutes / 60);
        const m = minutes % 60;
        if (h > 0) return `${h}h ${m}m`;
        return `${m}m`;
    }

    function formatDate(dateStr: string | undefined): string {
        if (!dateStr) return "";
        return new Date(dateStr).toLocaleString("th-TH", {
            day: "numeric",
            month: "short",
            hour: "2-digit",
            minute: "2-digit",
        });
    }

    function copyToClipboard() {
        if (!summary) return;

        const text = `
📊 Daily Report - ${logDate}
━━━━━━━━━━━━━━━━━━━━━

📝 ${summary.summary}

📈 สถิติรวม:
• Volume: ${formatVolume(summary.totalVolume)} USDT
• Transactions: ${summary.transactionCount}
• Buy: ${formatVolume(summary.buyVolume)} | Sell: ${formatVolume(summary.sellVolume)}

📊 Shift Breakdown:
• Shift A: ${formatVolume(summary.shiftStats.A.volume)} USDT (${summary.shiftStats.A.count} txns)
• Shift B: ${formatVolume(summary.shiftStats.B.volume)} USDT (${summary.shiftStats.B.count} txns)
• Shift C: ${formatVolume(summary.shiftStats.C.volume)} USDT (${summary.shiftStats.C.count} txns)

💡 Management Insights:
${summary.managementInsights.map((i) => `• ${i}`).join("\n")}

${summary.issues.length > 0 ? `⚠️ Issues:\n${summary.issues.map((i) => `• ${i}`).join("\n")}\n` : ""}
✅ Recommendations:
${summary.recommendations.map((r) => `• ${r}`).join("\n")}

Generated by: ${summary.provider} (${summary.model})
        `.trim();

        navigator.clipboard.writeText(text);
    }
</script>

<section class="daily-summary-container">
    <header class="section-header">
        <div class="header-left">
            <span class="icon">📊</span>
            <h3>Daily Report</h3>
            {#if summary}
                <span
                    class="provider-badge"
                    class:openai={summary.provider === "openai"}
                >
                    {summary.provider === "openai" ? "GPT-4" : "Gemini"}
                </span>
            {/if}
        </div>
        <div class="header-actions">
            {#if !loading}
                <!-- Provider Selector -->
                <div class="provider-selector">
                    <button
                        class="provider-btn"
                        class:active={selectedProvider === "auto"}
                        on:click={() => (selectedProvider = "auto")}
                        disabled={!providerStatus.openai &&
                            !providerStatus.gemini}
                        title="Auto">⚡</button
                    >
                    <button
                        class="provider-btn openai"
                        class:active={selectedProvider === "openai"}
                        on:click={() => (selectedProvider = "openai")}
                        disabled={!providerStatus.openai}
                        title="GPT-4">🟢</button
                    >
                    <button
                        class="provider-btn gemini"
                        class:active={selectedProvider === "gemini"}
                        on:click={() => (selectedProvider = "gemini")}
                        disabled={!providerStatus.gemini}
                        title="Gemini">🔵</button
                    >
                </div>

                <button
                    class="btn-generate"
                    on:click={generateSummary}
                    disabled={sessions.length === 0 ||
                        (!providerStatus.openai && !providerStatus.gemini)}
                >
                    {summary ? "🔄" : "✨"} Generate
                </button>
            {/if}
        </div>
    </header>

    <div class="content">
        {#if loading}
            <div class="loading-state">
                <div class="spinner"></div>
                <p>กำลังสร้าง Daily Report...</p>
            </div>
        {:else if error}
            <div class="error-state">
                <span>⚠️</span>
                <p>{error}</p>
                <button class="btn-retry" on:click={generateSummary}
                    >ลองใหม่</button
                >
            </div>
        {:else if !summary}
            <div class="empty-state">
                <span class="empty-icon">📋</span>
                <p>ยังไม่มี Daily Report สำหรับวันนี้</p>
                {#if sessions.length === 0}
                    <p class="hint">
                        ไม่มี Session - ไม่สามารถสร้าง Report ได้
                    </p>
                {:else}
                    <p class="hint">
                        กดปุ่ม "Generate" เพื่อสร้าง ({sessions.length} sessions)
                    </p>
                {/if}
            </div>
        {:else}
            <div class="summary-content">
                <!-- Stats Grid -->
                <div class="stats-grid">
                    <div class="stat-card primary">
                        <span class="stat-icon">📈</span>
                        <div class="stat-info">
                            <span class="stat-value"
                                >{formatVolume(summary.totalVolume)}</span
                            >
                            <span class="stat-label">USDT Volume</span>
                        </div>
                    </div>
                    <div class="stat-card">
                        <span class="stat-icon">🔄</span>
                        <div class="stat-info">
                            <span class="stat-value"
                                >{summary.transactionCount}</span
                            >
                            <span class="stat-label">Transactions</span>
                        </div>
                    </div>
                    <div class="stat-card buy">
                        <span class="stat-icon">▲</span>
                        <div class="stat-info">
                            <span class="stat-value"
                                >{formatVolume(summary.buyVolume)}</span
                            >
                            <span class="stat-label">Buy Volume</span>
                        </div>
                    </div>
                    <div class="stat-card sell">
                        <span class="stat-icon">▼</span>
                        <div class="stat-info">
                            <span class="stat-value"
                                >{formatVolume(summary.sellVolume)}</span
                            >
                            <span class="stat-label">Sell Volume</span>
                        </div>
                    </div>
                </div>

                <!-- AI Summary -->
                <div class="summary-card main">
                    <div class="card-header">
                        <span class="card-icon">🤖</span>
                        <span class="card-title">AI Summary</span>
                    </div>
                    <p class="summary-text">{summary.summary}</p>
                </div>

                <!-- Shift Breakdown -->
                <div class="shift-breakdown">
                    <div class="card-header">
                        <span class="card-icon">📊</span>
                        <span class="card-title">Shift Breakdown</span>
                    </div>
                    <div class="shift-table">
                        {#each ["A", "B", "C"] as shift (shift)}
                            {@const stats =
                                summary.shiftStats[shift as "A" | "B" | "C"]}
                            <div
                                class="shift-row"
                                class:best={summary.bestShift === shift}
                            >
                                <span class="shift-name">Shift {shift}</span>
                                <span class="shift-volume"
                                    >{formatVolume(stats.volume)} USDT</span
                                >
                                <span class="shift-count"
                                    >{stats.count} txns</span
                                >
                                {#if summary.bestShift === shift}
                                    <span class="best-badge">⭐ Best</span>
                                {/if}
                            </div>
                        {/each}
                    </div>
                </div>

                <!-- Insights -->
                {#if summary.managementInsights.length > 0}
                    <div class="summary-card insights">
                        <div class="card-header">
                            <span class="card-icon">💡</span>
                            <span class="card-title">Management Insights</span>
                        </div>
                        <ul class="insight-list">
                            {#each summary.managementInsights as insight}
                                <li>{insight}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}

                <!-- Issues -->
                {#if summary.issues.length > 0}
                    <div class="summary-card issues">
                        <div class="card-header">
                            <span class="card-icon">⚠️</span>
                            <span class="card-title">Issues</span>
                        </div>
                        <ul class="insight-list">
                            {#each summary.issues as issue}
                                <li>{issue}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}

                <!-- Recommendations -->
                {#if summary.recommendations.length > 0}
                    <div class="summary-card recommendations">
                        <div class="card-header">
                            <span class="card-icon">✅</span>
                            <span class="card-title">Recommendations</span>
                        </div>
                        <ul class="insight-list">
                            {#each summary.recommendations as rec}
                                <li>{rec}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}

                <!-- Footer -->
                <div class="summary-footer">
                    <span class="generated-info">
                        Generated: {formatDate(summary.created_at)}
                    </span>
                    <button class="btn-copy" on:click={copyToClipboard}>
                        📋 Copy Report
                    </button>
                </div>
            </div>
        {/if}
    </div>
</section>

<style>
    .daily-summary-container {
        background: var(--color-bg);
        border: 1px solid var(--color-border-light);
        border-radius: 16px;
        overflow: hidden;
        margin-bottom: 1.5rem;
    }

    .section-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem 1.25rem;
        background: linear-gradient(
            135deg,
            rgba(59, 130, 246, 0.1),
            rgba(16, 185, 129, 0.1)
        );
        border-bottom: 1px solid var(--color-border-light);
        flex-wrap: wrap;
        gap: 0.75rem;
    }

    .header-left {
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }

    .icon {
        font-size: 1.5rem;
    }

    .section-header h3 {
        margin: 0;
        font-size: 1.125rem;
        font-weight: 600;
        color: var(--color-text);
    }

    .provider-badge {
        padding: 0.25rem 0.5rem;
        font-size: 0.6875rem;
        font-weight: 600;
        border-radius: 6px;
        background: rgba(118, 75, 162, 0.15);
        color: #764ba2;
    }

    .provider-badge.openai {
        background: rgba(16, 163, 127, 0.15);
        color: #10a37f;
    }

    .header-actions {
        display: flex;
        gap: 0.5rem;
        align-items: center;
    }

    .provider-selector {
        display: flex;
        gap: 0.125rem;
        background: var(--color-bg-secondary);
        border-radius: 6px;
        padding: 0.125rem;
    }

    .provider-btn {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
        border: none;
        border-radius: 4px;
        background: transparent;
        cursor: pointer;
        transition: all 0.15s;
    }

    .provider-btn:hover:not(:disabled) {
        background: var(--color-bg-tertiary);
    }

    .provider-btn.active {
        background: var(--color-bg);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    }

    .provider-btn:disabled {
        opacity: 0.3;
        cursor: not-allowed;
    }

    .btn-generate {
        padding: 0.5rem 0.875rem;
        font-size: 0.8125rem;
        font-weight: 600;
        border: none;
        border-radius: 8px;
        background: linear-gradient(135deg, #3b82f6, #10b981);
        color: white;
        cursor: pointer;
        transition: all 0.2s;
    }

    .btn-generate:hover:not(:disabled) {
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
    }

    .btn-generate:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .content {
        padding: 1.25rem;
    }

    /* Loading & Empty States */
    .loading-state,
    .empty-state,
    .error-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 0.5rem;
        padding: 2rem;
        text-align: center;
    }

    .spinner {
        width: 32px;
        height: 32px;
        border: 3px solid var(--color-border-light);
        border-top-color: #3b82f6;
        border-radius: 50%;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }

    .empty-icon {
        font-size: 2.5rem;
        opacity: 0.5;
    }

    .empty-state p,
    .loading-state p {
        margin: 0;
        color: var(--color-text-tertiary);
    }

    .hint {
        font-size: 0.8125rem;
    }

    .error-state {
        background: rgba(255, 59, 48, 0.1);
        border-radius: 12px;
    }

    .error-state p {
        color: #ff3b30;
    }

    .btn-retry {
        padding: 0.375rem 0.75rem;
        font-size: 0.8125rem;
        background: var(--color-bg);
        border: 1px solid var(--color-border-light);
        border-radius: 6px;
        cursor: pointer;
    }

    /* Summary Content */
    .summary-content {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    /* Stats Grid */
    .stats-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 0.75rem;
    }

    @media (max-width: 768px) {
        .stats-grid {
            grid-template-columns: repeat(2, 1fr);
        }
    }

    .stat-card {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        padding: 0.875rem;
        background: var(--color-bg-secondary);
        border-radius: 12px;
    }

    .stat-card.primary {
        background: linear-gradient(
            135deg,
            rgba(59, 130, 246, 0.15),
            rgba(59, 130, 246, 0.05)
        );
    }

    .stat-card.buy {
        background: rgba(52, 199, 89, 0.1);
    }

    .stat-card.sell {
        background: rgba(255, 59, 48, 0.1);
    }

    .stat-icon {
        font-size: 1.25rem;
    }

    .stat-info {
        display: flex;
        flex-direction: column;
        gap: 0.125rem;
    }

    .stat-value {
        font-size: 1.125rem;
        font-weight: 700;
        color: var(--color-text);
    }

    .stat-label {
        font-size: 0.6875rem;
        color: var(--color-text-tertiary);
        text-transform: uppercase;
    }

    /* Summary Cards */
    .summary-card {
        padding: 1rem;
        background: var(--color-bg-secondary);
        border-radius: 12px;
    }

    .summary-card.main {
        background: linear-gradient(
            135deg,
            rgba(59, 130, 246, 0.08),
            rgba(16, 185, 129, 0.08)
        );
    }

    .summary-card.issues {
        background: rgba(255, 149, 0, 0.1);
        border: 1px solid rgba(255, 149, 0, 0.2);
    }

    .card-header {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        margin-bottom: 0.75rem;
    }

    .card-icon {
        font-size: 1rem;
    }

    .card-title {
        font-size: 0.8125rem;
        font-weight: 600;
        color: var(--color-text-secondary);
    }

    .summary-text {
        margin: 0;
        font-size: 0.9375rem;
        line-height: 1.6;
        color: var(--color-text);
    }

    /* Shift Breakdown */
    .shift-breakdown {
        padding: 1rem;
        background: var(--color-bg-secondary);
        border-radius: 12px;
    }

    .shift-table {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    .shift-row {
        display: flex;
        align-items: center;
        gap: 1rem;
        padding: 0.625rem 0.75rem;
        background: var(--color-bg);
        border-radius: 8px;
    }

    .shift-row.best {
        background: rgba(52, 199, 89, 0.1);
        border: 1px solid rgba(52, 199, 89, 0.2);
    }

    .shift-name {
        font-weight: 600;
        color: var(--color-text);
        min-width: 60px;
    }

    .shift-volume {
        flex: 1;
        font-weight: 500;
        color: var(--color-text-secondary);
    }

    .shift-count {
        font-size: 0.8125rem;
        color: var(--color-text-tertiary);
    }

    .best-badge {
        font-size: 0.6875rem;
        font-weight: 600;
        color: #34c759;
    }

    /* Insight List */
    .insight-list {
        margin: 0;
        padding-left: 1.25rem;
        font-size: 0.9375rem;
        line-height: 1.6;
        color: var(--color-text-secondary);
    }

    .insight-list li {
        margin-bottom: 0.375rem;
    }

    /* Footer */
    .summary-footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding-top: 1rem;
        border-top: 1px solid var(--color-separator);
    }

    .generated-info {
        font-size: 0.75rem;
        color: var(--color-text-tertiary);
    }

    .btn-copy {
        padding: 0.375rem 0.75rem;
        font-size: 0.8125rem;
        font-weight: 500;
        background: var(--color-bg-secondary);
        border: 1px solid var(--color-border-light);
        border-radius: 6px;
        cursor: pointer;
        transition: all 0.15s;
    }

    .btn-copy:hover {
        background: var(--color-bg-tertiary);
    }
</style>
